### ISSUE TITLE
Recipe Serialization

### ISSUE THREAD

**Issue by JustKade** [Moralle/VanillaCookbook#3]
Hello

Your mod has appeared to messed up with the recipe serialization and wouldn't allow anyone to join a multiplayer server. 

Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.toString()" because "p_130086_" is null

This is all I have since I found out by accident that the mod was the culprit.

**Comment by BILLYx1120** [comment]
Have the same issue. Was making a mod pack containing most of the farmer's delight and its relevants and this mod really gave me a hard time diagnosing the problem.

**Comment by Kelpiesaurus** [comment]
I'm afraid I am getting the same error when trying to connect to a sever with the Adagio modpack, which includes Vanilla Cookbook.

**Comment by Moralle** [comment]
I just released an update that I hope will fix this issue. I'm not 100% sure since custom recipe serialization is still rather new to me, so I'll keep this open for now until someone can confirm that it's actually fixed.

**Comment by BILLYx1120** [comment]
Hi, sorry to send a message tonight, but the 2.1.1 version also didn't work.

![toStrIsNull](https://github.com/Moralle/VanillaCookbook/assets/20014530/ac94db9a-b0aa-4747-830e-3dfbd57d9056)

This is the log when I tried to log in to my server. I've covered all personal data. 
The sentence underlined is exactly what I saw on the client side, and I have no clue what happened. Some suggest it might be because my folder path contains non-English characters. I've tried addressing that, but that's not the issue.

Thank you for fixing this, and happy new year!

**Comment by Moralle** [comment]
Okay, I made another fix in 2.1.2 and this time I'm fairly confident that it should have done the trick, but I'll still wait for confirmation

**Comment by BILLYx1120** [comment]
Yes!! The new 2.1.2 version fixes the problem and finally I can play around with this mod. Thanks a lot!

**Comment by Moralle** [comment]
Thanks for the confirmation, and for the patience! Glad I was finally able to resolve this.
