### ISSUE TITLE
[Bug?] Some recipes don't use forge:milk

### ISSUE THREAD

**Issue by CherryPuppet** [Moralle/VanillaCookbook#5]
Snow Horns, Chocolate Milk, and Berry Milk don't use forge:milk for their recipes.

Snow Horn recipe, it only accepts milk from this mod and vanilla:
![2024-07-10_17 37 21](https://github.com/Moralle/VanillaCookbook/assets/162679788/3d614739-7f5f-4a79-a35a-d8c2bea4f3e6)

Bacon Pancake recipe, it is compatible with milk from other mods:
![2024-07-10_17 37 55](https://github.com/Moralle/VanillaCookbook/assets/162679788/2b3b13c5-be44-4e0b-959b-39bbcaec4f83)

**Comment by Moralle** [comment]
These recipes are intended this way. The two milk items specifically use VC's milk bottles since the bottle gets converted directly into the new item, which frees the player from needing another bottle. They, along with the Snow Horn, also use a custom recipe type, which does not work with tag ingredients.
